name: Test
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: Test and lint code
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
      - name: Lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run